version: "2.2"
services:
  web_1:
    cpus: 0.05
    mem_limit: 1000000000
    image: localhost:500/web_1:1.0
    ports:
      - "5555:5555"
    volumes:
      - ./vol:/usr/share/nginx/html
  web_2:
    cpus: 0.05
    mem_limit: 1000000000
    image: localhost:500/web_2:1.0
    ports:
      - "7777:7777"
    volumes:
      - ./vol:/usr/share/nginx/html
